const fs=require('node:fs');
const assert=require('node:assert/strict');
const app=fs.readFileSync('public/app.js','utf8');
const transport=fs.readFileSync('public/transport.js','utf8');
assert.match(app,/function enterViewerConnection[\s\S]*?ensureLiveStateSubscription\(window\.ATEM_TRANSPORT\)/,'Viewer must subscribe to live state when entering Viewer mode');
assert.match(app,/function disconnectShowDesk[\s\S]*?clearLiveStateSubscription\(\)/,'Disconnect must clear the active live-state subscription');
assert.match(app,/connectionInputChanged\(\);viewerInputChanged\(\)/,'Disconnect must revalidate retained Host and Viewer addresses');
assert.match(transport,/function connectViewer[\s\S]*?viewerSocket = viewer/,'Direct Viewer socket must be tracked');
assert.match(transport,/disconnectViewer\(\) \{[\s\S]*?viewerSocket[\s\S]*?viewer\.close\(\)/,'Viewer disconnect must close the direct Viewer socket');
const directDisconnect=transport.slice(transport.indexOf('disconnectViewer() {'));
assert.ok(!directDisconnect.includes("request('disconnectViewerHost'")&&!directDisconnect.includes('request("disconnectViewerHost"'),'Direct Viewer disconnect must not use the retired backend relay');
assert.match(transport,/subscribeHealth\(callback\)/,'Transport must expose read-only health subscriptions');
assert.match(transport,/msg\.type === 'health'/,'Transport must forward Host health heartbeats');
assert.match(app,/transport\.subscribe\(\(patch\)=>\{markConnectionActivity\(\)/,'Live state must count as healthy connection activity');
assert.ok(!app.includes('• STALE'),'Operator-facing connection status must not show STALE while the transport remains connected');
assert.match(app,/function startConnectionHealth[\s\S]*?subscribeHealth/,'Connected Host and Viewer modes must subscribe to health events');
assert.match(app,/function stopConnectionHealth[\s\S]*?clearInterval/,'Disconnect must clean up connection health monitoring');
assert.match(app,/text\.textContent=activeConnectionMode\.toUpperCase\(\)\+" • CONNECTED"/,'Connected Host and Viewer modes must remain operator-facing CONNECTED');
console.log('Viewer lifecycle and connection-health regression checks passed');
