const fs=require('node:fs');
const assert=require('node:assert/strict');
const app=fs.readFileSync('public/app.js','utf8');
const transport=fs.readFileSync('public/transport.js','utf8');
assert.match(app,/function enterViewerConnection[\\s\\S]*?ensureLiveStateSubscription\\(window\\.ATEM_TRANSPORT\\)/,'Viewer must subscribe to live state when entering Viewer mode');
assert.match(app,/function disconnectShowDesk[\\s\\S]*?clearLiveStateSubscription\\(\\)/,'Disconnect must clear the active live-state subscription');
assert.match(app,/connectionInputChanged\\(\\);viewerInputChanged\\(\\)/,'Disconnect must revalidate retained Host and Viewer addresses');
assert.match(transport,/function connectViewer[\\s\\S]*?viewerSocket = viewer/,'Direct Viewer socket must be tracked');
assert.match(transport,/disconnectViewer\\(\\) \\{[\\s\\S]*?viewerSocket[\\s\\S]*?viewer\\.close\\(\\)/,'Viewer disconnect must close the direct Viewer socket');
assert.doesNotMatch(transport,/disconnectViewer\\(\\)[^{]*\\{[^}]*request\\(['"]disconnectViewerHost/,'Direct Viewer disconnect must not use the retired backend relay');
console.log('Viewer lifecycle regression checks passed');
